name: sync-homebrew

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The git tag name to bump the cask to'
        required: false
        type: string
        default: 'refs/tags/v1.x.x'
  workflow_run:
    workflows: ['release-assets']
    types:
      - completed

jobs:
  sync-homebrew:
    runs-on: macos-latest
    steps:
    - uses: eugenesvk/action-homebrew-bump-cask@c5357e045eb291820713d22f7d1a2a379b409ddd
      with:
        tap: viarotel-org/homebrew-escrcpy
        cask: escrcpy
        token: ${{secrets.GH_TOKEN}}
        tag: ${{ github.event.inputs.tag || github.ref }}